description: >
  Just a debug/testing dataset from finn rietz.
  currently not sure what role the 'format: tb100zip' attribute playes, leaving it unchanged.
format: tb100zip
samples:
    - name: BikerStatic
      attributes: [FM, LR, MB, OCC, OPR, OV, SV]
      actual_frames: 50