# tracker.yaml
# defines how the tracker is set up and what samples will be tracked
# Can be fed to program via command line argument --tracker [path]

#sroi_size: [368, 368]
#sroi_size: [50, 50]
#sroi_size: [960, 720]
roi_scale: [2.0, 2.0]
roi_movement_factor: 0.0
sroi_size: [200, 200]
#sroi_scale: 0.5
mask_size:
#extractor_net: alexnet
#features:
#  - [conv4, 256]
#  - [conv5, 128]
extractor_net: vgg16
features:
- [conv4_3, 384]
#  - [conv5_3, 384]
#  - [conv4_3, 60]
- [conv5_3, 384]
#  - [pool3, 64]
random_seed: 1338
selector:
  max_iterations: 50
  min_cost:
  net:
    name: selector_net
    cost: mean_square
    optimizer: [adam, learning_rate: 0.000001]
    layers:
    - type: dropout
      name: dropout
      keep_prob: 0.7
    - type: conv
      name: conv1
        #weight_initial: [truncated_normal, {stddev: 0.1}]
      weight_initial: [truncated_normal, stddev: 0.0000001]
      bias_initial: zeros
      kernel_size: 3
      channels: 1

consolidator:
  max_iterations: 20
  min_cost: 0.0005
  sigma_train: 0.8
  sigma_update: 0.8
  update_threshold: 0.2
  update_lower_threshold: 0.4
  # number of frames stored for updates
  update_frame_store_size: 5
  # number of training cycles for update
  update_max_iterations: 2
  # update_max_frames: number of frames until update of consolidator is forced. Use null for never
  update_max_frames:
  # update_min_frames: number of frames that must have passed since the last update of consolidator (hard limit). Use null or (0 or 1) for no limit
  update_min_frames:
  update_keep_initial_frame: true
  update_initial_factor: 4.0
  update_use_quality: false
  update_current_factor: 1.0
  net:
    name: consolidator_net
    cost: mean_square
#    optimizer: [adam, {learning_rate: 0.000000001}]
    optimizer: [adam, learning_rate: 0.00001]
#    optimizer: [momentum, {learning_rate: 0.00001, momentum: 0.6}]
    layers:
    - type: conv
      name: conv1
      weight_initial: [truncated_normal, stddev: 0.0000001]
      bias_initial: 0.1
      kernel_size: 9
      channels: 32
    - type: activation
      name: activation1
      function: crelu
    - type: conv
      name: conv2
      weight_initial: [truncated_normal, stddev: 0.0000001]
      bias_initial: 0
      kernel_size: 5
      channels: 1

pursuer:
  particle_count: 600
  particle_scale_factor: 1.0
  target_lower_limit: 0.2
  target_punish_low: 0.0
  target_punish_outside: 0.0

tracking_conf:
  fake_fps: 0
  skip_frames: 0
  shuffle: false

scale_estimator:
  use_scale_estimation: true   # Enable or disable scale estimation
  update_strategy: cont
  dyn_min_se_treshold: 0.2
  dyn_max_se_treshold: 0.4
  static_update_val: 20

  # Determines which approach to use for scale estimation. candidates or custom_dsst
  approach: custom_dsst

  #dsst params:
  scale_factor: 1.02  # scale factor between scale lvls
  scale_sigma_factor: 0.25 # changes the deviation/sharpness of the output gaussian
  learning_rate: 0.025
  reg: 0.01
  scale_model_max: 512 # max area of the scale model on the image
  scale_model_size: 16
  padding: 1.0
  dsst_number_scales: 25 # number of scaled candidates to generate
  d_change_aspect_ratio: false
  hog_cell_size: 1
  hog_block_norm_size: 4

  # candidate params:
  c_scale_factor: 1.02 # scale factor between candidates
  c_change_aspect_ratio: false # change aspect ratio of bouding box
  inner_punish_threshold: 0.3 # the threshold at which a bounding box gets punish for containing pixels scores smaller than the threshold
  outer_punish_threshold: 0.3 # the threshold at which a bounding box gets punished for not containing pixels scores bigger than the threshold
  c_number_scales: 17 # number of scaled candidates to generate
  max_scale_difference: 0.02 # max value the scale may change between two frames
  scale_window_step_size: 0.005 # the deviation value for the manual scale window calculation which punishes the candidates based on the divergence to one
  adjust_max_scale_diff: false # adjust the max_scale_difference value if the factor has been limited n time sin a row, necessary for extreme scale changes that exceed the max_scale_difference between frames
  adjust_max_scale_diff_after: 3 # the number after how many times of the scale factor being limited the max scale_difference gets adjusted




# = tracking =
# which samples shall be tracked? Accepts samples, data sets, and data collections
# examples: ['tb100/MotorRolling', 'SET/tb100', 'COLLECTION/tb100_probe']
tracking:
# = Short Test Set = #
#- tb100/Deer
#- tb100/DragonBaby
#- tb100/CarScale
#- tb100/Walking

# = Training Set = #
- tb100/Basketball
- tb100/Biker
- tb100/Bird2
- tb100/Box
- tb100/Freeman3
- tb100/Panda
- tb100/ClifBar
- tb100/Crowds
- tb100/RedTeam
- tb100/BlurFace
- tb100/Singer2
- tb100/Soccer
- tb100/Car1
- tb100/Liquor
- tb100/Bird1
- tb100/DragonBaby
- tb100/Deer
- tb100/Diving
- tb100/Dudek
- tb100/David

# = TB100 = #
#- tb100/Basketball
#- tb100/Biker
#- tb100/Bird1
#- tb100/Bird2
#- tb100/BlurBody
#- tb100/BlurCar1
#- tb100/BlurCar2
#- tb100/BlurCar3
#- tb100/BlurCar4
#- tb100/BlurFace
#- tb100/BlurOwl
#- tb100/Board
#- tb100/Bolt
#- tb100/Bolt2
#- tb100/Box
#- tb100/Boy
#- tb100/Car1
#- tb100/Car2
#- tb100/Car24
#- tb100/Car4
#- tb100/CarDark
#- tb100/CarScale
#- tb100/ClifBar
#- tb100/Coke
#- tb100/Couple
#- tb100/Coupon
#- tb100/Crossing
#- tb100/Crowds
#- tb100/Dancer
#- tb100/Dancer2
#- tb100/David
#- tb100/David2
#- tb100/David3
#- tb100/Deer
#- tb100/Diving
#- tb100/Dog
#- tb100/Dog1
#- tb100/Doll
#- tb100/DragonBaby
#- tb100/Dudek
#- tb100/FaceOcc1
#- tb100/FaceOcc2
#- tb100/Fish
#- tb100/FleetFace
#- tb100/Football
#- tb100/Football1
#- tb100/Freeman1
#- tb100/Freeman3
#- tb100/Freeman4
#- tb100/Girl
#- tb100/Girl2
#- tb100/Gym
#- tb100/Human2
#- tb100/Human3
#- tb100/Human4
#- tb100/Human5
#- tb100/Human6
#- tb100/Human7
#- tb100/Human8
#- tb100/Human9
#- tb100/Ironman
#- tb100/Jogging1
#- tb100/Jogging2
#- tb100/Jump
#- tb100/Jumping
#- tb100/KiteSurf
#- tb100/Lemming
#- tb100/Liquor
#- tb100/Man
#- tb100/Matrix
#- tb100/Mhyang
#- tb100/MotorRolling
#- tb100/MountainBike
#- tb100/Panda
#- tb100/RedTeam
#- tb100/Rubik
#- tb100/Shaking
#- tb100/Singer1
#- tb100/Singer2
#- tb100/Skater
#- tb100/Skater2
#- tb100/Skating1
#- tb100/Skating2
#- tb100/Skating3
#- tb100/Skiing
#- tb100/Soccer
#- tb100/Subway
#- tb100/Surfer
#- tb100/Suv
#- tb100/Sylvester
#- tb100/Tiger1
#- tb100/Tiger2
#- tb100/Toy
#- tb100/Trans
#- tb100/Trellis
#- tb100/Twinnings
#- tb100/Vase
#- tb100/Walking
#- tb100/Walking2
#- tb100/Woman

#  - ros/nico/vision/videoStream
#  - nico_recordings/banana
#  - nico_recordings/cube
#  - nico_recordings/grapes
#  - nico_recordings/tomato
#  - nico_recordings/tomato_and_carrot.1
#  - nico_recordings/tomato_and_carrot.2
#  - tb100/David
#  - tb100/Panda
#  - tb100/Basketball
#  - tb100/RedTeam
#  - tb100/Liquor
#  - tb100/Coke
#  - tb100/Matrix
#  - tb100/MotorRolling
#  - tb100/Soccer
#  - tb100/Freeman3
#  - tb100/Lemming
#  - tb100/Tiger2
#  - tb100/Jumping
#  - tb100/Ironman
#  - tb100/Twinnings
#  - tb100/CarScale
#  - COLLECTION/tb100_probe
#  - COLLECTION/tb100_paper50
#  - princeton/zcup_move_1
#  - princeton/cup_book
#  - princeton/computerBar2
#  - SET/princeton
#  - princeton/book_turn
#  - nicovision/bang_sponge_01
#  - nicovision/lift_sponge_02
#  - nicovision/shake_small_banana_02
#  - nicovision/scoot_blue_ball_02
#  - nicovision/lift_blue_car_05
#  - nicovision/shake_heavy_banana_03
#  - nicovision/bang_blue_tissue_01
#  - nicovision/lift_blue_car_01
#  - nicovision/lift_blue_car_02
#  - nicovision/lift_blue_car_03
#  - nicovision/lift_blue_car_04
#  - nicovision/lift_blue_tissue_01
#  - nicovision/lift_heavy_banana_01
#  - nicovision/lift_heavy_banana_02
#  - nicovision/lift_red_car_01
#  - nicovision/lift_red_car_02
#  - nicovision/lift_small_yellow_cube_01
#  - nicovision/lift_sponge_02
#  - nicovision/lift_sponge_03
#  - nicovision/lift_styrofoam_cube_01
#  - nicovision/pull_blue_ball_01
#  - nicovision/pull_blue_car_01
#  - nicovision/pull_blue_plush_ball_01
#  - nicovision/pull_blue_tissue_01
#  - nicovision/pull_brown_plush_ball_01
#  - nicovision/pull_green_car_01
#  - nicovision/pull_heavy_apple_01
#  - nicovision/pull_heavy_tomato_01
#  - nicovision/pull_heavy_yellow_cube_01
#  - nicovision/pull_orange_patterned_plush_ball_01
#  - nicovision/pull_red_car_01
#  - nicovision/pull_red_car_02
#  - nicovision/pull_small_tomato_01
#  - nicovision/pull_small_yellow_cube_01
#  - nicovision/pull_sponge_01
#  - nicovision/pull_styrofoam_cube_01
#  - nicovision/pull_styrofoam_cube_02
#  - nicovision/push_blue_ball_01
#  - nicovision/push_blue_car_01
#  - nicovision/push_blue_car_02
#  - nicovision/push_blue_patterned_plush_ball_01
#  - nicovision/push_green_car_01
#  - nicovision/push_green_car_02
#  - nicovision/push_heavy_apple_01
#  - nicovision/push_heavy_apple_02
#  - nicovision/push_red_car_01
#  - nicovision/push_red_car_02
#  - nicovision/push_small_yellow_cube_01
#  - nicovision/push_sponge_01
#  - nicovision/scoot_blue_ball_01
#  - nicovision/scoot_blue_car_01
#  - nicovision/scoot_blue_car_02
#  - nicovision/scoot_blue_tissue_01
#  - nicovision/scoot_green_car_01
#  - nicovision/scoot_plush_banana_01
#  - nicovision/shake_big_light_banana_01
#  - nicovision/shake_blue_plush_ball_01
#  - nicovision/shake_blue_tissue_01
#  - nicovision/shake_brown_plush_ball_01
#  - nicovision/shake_heavy_banana_01
#  - nicovision/shake_heavy_banana_02
#  - nicovision/shake_heavy_banana_03
#  - nicovision/shake_heavy_banana_04
#  - nicovision/shake_red_tissue_01
#  - nicovision/shake_small_banana_01
#  - nicovision/shake_small_banana_02
#  - nicovision/shake_small_banana_03
#  - nicovision/shake_small_banana_04
#  - nicovision/shake_small_banana_05
#  - nicovision/shake_small_yellow_cube_01
#  - nicovision/shake_sponge_01
#  - nicovision/shake_styrofoam_cube_01
#  - nicovision/lift_sponge_01
#  - nicovision/pull_red_tissue_01
#  - nicovision/push_tomato_01

xtracking:
#  - tb100/SHORT
#  - tb100/SHORT
#  - tb100/SHORT
- tb100/Basketball
- tb100/Biker
- tb100/Bird1
- tb100/Bird2
- tb100/BlurBody
- tb100/BlurCar1
- tb100/BlurCar2
- tb100/BlurCar3
- tb100/BlurCar4
- tb100/BlurFace
- tb100/BlurOwl
- tb100/Board
- tb100/Bolt
- tb100/Bolt2
- tb100/Box
- SET/tb100
- tb50_paper
- tb100/Boy
- tb100/Car1
- tb100/Car2
- tb100/Car4
- tb100/Car24
- tb100/Dancer
- tb100/MotorRolling
- tb100/Deer

